# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosts',
            name='id',
        ),
        migrations.AlterField(
            model_name='hosts',
            name='hosts_hosts',
            field=models.CharField(help_text='host name, IP address or name.', max_length=128, primary_key=True,
                                   serialize=False),
        ),
    ]
